import localFont from "next/font/local";

/*
  The mono face, subset to what this app can actually print in it.

  Geist Mono ships 889 glyphs: Cyrillic, Greek, and 128 box-drawing and
  quadrant characters. Every one of them was downloaded by every visitor, and
  woff2 is already compressed, so unlike the JavaScript and the CSS this was
  weight that no amount of gzip on the wire was going to take back. Subset it
  is 46% smaller.

  Nothing in this app sets user-entered text in mono. The `.figure` class is
  money, percents, counts, ranks, dates and the invite code, all of it
  generated by the app. Display names and league names, which a player may
  write in any script they like, are set in the sans face -- and that one is
  left exactly as the package ships it, for that reason.

  What is in the subset is decided by MONO_SUBSET_RANGES in
  src/lib/brand/mono-subset.ts, which is also what `npm run fonts` builds the
  file from and what the tests check. One list, three users, so the font on
  disk cannot drift from what the app expects to find in it.

  The trap worth knowing about: the pasteable share text draws a week as block
  elements, U+2581 to U+2588, and sets them in mono like everything else in
  that block. Dropping them would break no build and fail no type. It would
  quietly turn the shape somebody pastes into a group chat into eight fallback
  glyphs, and only they would ever see it. There is a test for exactly that.
*/
export const geistMono = localFont({
  src: "../../assets/fonts/GeistMono-Variable.subset.woff2",
  variable: "--font-geist-mono",
  display: "swap",
  weight: "100 900",
  /*
    No synthesised fallback metrics. Next measures a fallback face against the
    real one to stop text reflowing when the webfont swaps in, but it does
    that from the font's own name, and a subset file is not a name it knows.
    The stack below is monospace either way, so the widths are already close.
  */
  adjustFontFallback: false,
  fallback: ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
});
